# Generated by Django 5.1.3 on 2024-12-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IN", "Insulation"),
                            ("WD", "Wood"),
                            ("MN", "Masonry"),
                            ("ST", "Stone"),
                            ("CR", "Concrete"),
                            ("FN", "Finish"),
                            ("SS", "Stud Layer [Steel Stud]"),
                            ("WS", "Stud Layer [Wood Stud]"),
                            ("AH", "Air [Horizontal Heat Flow]"),
                            ("AU", "Air [Upward Heat Flow]"),
                            ("AD", "Air [Downward Heat Flow]"),
                            ("MT", "Metal"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Material Categories",
                "ordering": ["category"],
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AddField(
            model_name="material",
            name="color_argb",
            field=models.CharField(default="255,255,255,255", max_length=16),
        ),
        migrations.AddField(
            model_name="material",
            name="comments",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="conductivity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="material",
            name="emissivity",
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name="material",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="641027", max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="webportal.materialcategory",
            ),
        ),
    ]
