# Generated by Django 5.1.3 on 2024-12-07 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IN", "Insulation"),
                            ("WD", "Wood"),
                            ("MN", "Masonry"),
                            ("ST", "Stone"),
                            ("CR", "Concrete"),
                            ("FN", "Finish"),
                            ("SS", "Steel_Stud_Layer"),
                            ("WS", "Wood_Stud_Layer"),
                            ("AH", "Air_Horizontal_Heat_Flow"),
                            ("AU", "Air_Upward_Heat_Flow"),
                            ("AD", "Air_Downward_Heat_Flow"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Material Categories",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="color_argb",
            field=models.CharField(default="255,255,255,255", max_length=16),
        ),
        migrations.AddField(
            model_name="material",
            name="comments",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="conductivity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="material",
            name="emissivity",
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name="material",
            name="source",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webportal.materialcategory",
            ),
        ),
    ]
