# Generated by Django 5.1.3 on 2024-12-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("webportal", "0002_customgroup_user_group"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomGroup",
            new_name="Team",
        ),
    ]
