# Generated by Django 5.1.3 on 2024-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0002_materialcategory_material_color_argb_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="materialcategory",
            options={
                "ordering": ["category"],
                "verbose_name_plural": "Material Categories",
            },
        ),
        migrations.AlterField(
            model_name="materialcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("IN", "Insulation"),
                    ("WD", "Wood"),
                    ("MN", "Masonry"),
                    ("ST", "Stone"),
                    ("CR", "Concrete"),
                    ("FN", "Finish"),
                    ("SS", "Stud Layer [Steel Stud]"),
                    ("WS", "Stud Layer [Wood Stud]"),
                    ("AH", "Air [Horizontal Heat Flow]"),
                    ("AU", "Air [Upward Heat Flow]"),
                    ("AD", "Air [Downward Heat Flow]"),
                ],
                max_length=2,
            ),
        ),
    ]
