# Generated by Django 5.1.3 on 2024-12-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0002_materialcategory_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="webportal.materialcategory",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="e42781", max_length=6, unique=True),
        ),
    ]
