# Generated by Django 5.1.3 on 2024-12-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0003_alter_material_category_alter_material_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="32fa7a", max_length=6, unique=True),
        ),
    ]
