# Generated by Django 5.1.3 on 2024-12-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0003_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
