# Generated by Django 5.1.3 on 2024-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0003_rename_customgroup_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="group",
            new_name="team",
        ),
    ]
