# Generated by Django 5.1.3 on 2024-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0004_rename_group_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_paid_user",
            field=models.BooleanField(default=False),
        ),
    ]
