# Generated by Django 5.1.3 on 2024-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0005_alter_materialcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("IN", "Insulation"),
                    ("WD", "Wood"),
                    ("MN", "Masonry"),
                    ("ST", "Stone"),
                    ("CR", "Concrete"),
                    ("FN", "Finish"),
                    ("SS", "Stud Layer [Steel Stud]"),
                    ("WS", "Stud Layer [Wood Stud]"),
                    ("AH", "Air [Horizontal Heat Flow]"),
                    ("AU", "Air [Upward Heat Flow]"),
                    ("AD", "Air [Downward Heat Flow]"),
                    ("MT", "Metal"),
                ],
                max_length=2,
                unique=True,
            ),
        ),
    ]
