# Generated by Django 5.1.3 on 2024-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0005_container_alter_material_unique_id_cell"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Container",
            new_name="Assembly",
        ),
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="32a6ed", max_length=6, unique=True),
        ),
    ]
