# Generated by Django 5.1.3 on 2024-12-18 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0005_user_is_paid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
