# Generated by Django 5.1.3 on 2024-12-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0006_team_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team_invite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to="webportal.team",
            ),
        ),
    ]
