# Generated by Django 5.1.3 on 2024-12-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0006_alter_materialcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="webportal.materialcategory",
            ),
            preserve_default=False,
        ),
    ]
