# Generated by Django 5.1.3 on 2024-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0007_assembly_user_alter_material_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="41573d", max_length=6, unique=True),
        ),
    ]
