# Generated by Django 5.1.3 on 2024-12-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0007_user_team_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="user",
        ),
        migrations.AddField(
            model_name="assembly",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assemblies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=12, null=True)),
                ("name", models.CharField(default="new project", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assembly_id_order", models.JSONField(default=list)),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assembly",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="webportal.project",
            ),
        ),
    ]
