# Generated by Django 5.1.3 on 2024-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0008_alter_material_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="4e3bd0", max_length=6, unique=True),
        ),
    ]
