# Generated by Django 5.1.3 on 2024-12-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0009_alter_material_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="column_number",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="container",
        ),
        migrations.RemoveField(
            model_name="cell",
            name="row_number",
        ),
        migrations.AddField(
            model_name="assembly",
            name="layer_id_order",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="90dd06", max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thickness", models.FloatField()),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="webportal.assembly",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cell",
            name="layer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="webportal.layer",
            ),
        ),
    ]
