# Generated by Django 5.1.3 on 2024-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0010_remove_cell_column_number_remove_cell_container_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="2d95fc", max_length=6, unique=True),
        ),
    ]
