# Generated by Django 5.1.3 on 2024-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webportal", "0011_alter_material_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unique_id",
            field=models.CharField(default="7f013d", max_length=6, unique=True),
        ),
    ]
